# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# maketable.py
# Created on: 2015-09-24 15:52:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Tablaexp = "C:\\Users\\fgonzalezf\\Documents\\Monica_Forigua\\Pruebas_NBS\\enviar25.mdb\\Tablaexp"
QueryTable = "QueryTable"

# Process: Make Query Table
arcpy.MakeQueryTable_management("C:\\Users\\fgonzalezf\\Documents\\Monica_Forigua\\Pruebas_NBS\\enviar25.mdb\\Tablaexp", QueryTable, "USE_KEY_FIELDS", "", "Tablaexp.ACTION_CODE ACTION_CODE;Tablaexp.POI_PVID POI_PVID;Tablaexp.PS3_BLEND_POI_ID #;Tablaexp.FACILITY_CODE_ #;Tablaexp.POI_NAME_LANG_CODE #;Tablaexp.POI_NAME_ #;Tablaexp.POI_ADDRESS_LANG_CODE #;Tablaexp.ADDRESS_NUMBER #;Tablaexp.COUNTRY_ #;Tablaexp.LATITUDE_ #;Tablaexp.LONGITUDE_ #;Tablaexp.PHONE_NUMBER_ #;Tablaexp.CHAIN_ID_ #;Tablaexp.CUISINE_ID #;Tablaexp.BUILDING_TYPE #;Tablaexp.SUPPLIER_POI_ID #;Tablaexp.STREET_BASE_NAME #;Tablaexp.POSTAL_CODE_ #;Tablaexp.PROTECTED_ID #;Tablaexp.CALL_REVIEW_DATE #;Tablaexp.SOURCE_CODE #;Tablaexp.NUMBER_ #;Tablaexp.STREET_SIDE_ #", "")

